---

- name: install | ensure postgresql service is installed
  apt:
    name: ['postgresql', 'postgresql-contrib', 'python3-psycopg2']
    state: present

- name: install | ensure postgresql is running and enabled
  systemd:
    name: postgresql
    state: started
    enabled: yes
