---

- name: install | Ensure ssl-cert is installed
  apt:
    name: ssl-cert
    state: present

- name: install | Ensure nginx is installed
  apt:
    name: nginx
    state: present

- name: install | Ensure nginx is running and enabled
  systemd:
    name: nginx
    state: started
    enabled: yes
  ignore_errors: true