---

- name: install | ensure rabbitmq-server is installed
  apt:
    name: rabbitmq-server
    state: present

- name: install | ensure rabbitmq-server is running and enabled
  systemd:
    name: rabbitmq-server
    state: started
    enabled: yes

