---

- name: systemd | rabbitmq-server | started
  systemd:
    name: rabbitmq-server
    state: started

- name: systemd | rabbitmq-server | stopped
  systemd:
    name: rabbitmq-server
    state: stopped

- name: systemd | rabbitmq-server | restarted
  systemd:
    name: rabbitmq-server
    state: restarted

- name: systemd | rabbitmq-server | reloaded
  systemd:
    name: rabbitmq-server
    state: reloaded

- name: systemd | reload
  systemd:
    daemon_reload: yes