---

- hosts: localhost
  gather_facts: true
  vars:
    base_image: "debian/stretch/amd64"
    instance_name: awx-debian9-experimental
    action: start
  roles:
  - lxd-container

- hosts: "{{ hostvars.localhost.container_name }}"
  gather_facts: false
  roles:
  - python2

- hosts: "{{ hostvars.localhost.container_name }}"
  gather_facts: true
  vars:
    target_distribution: "Debian"
    target_distribution_major_version: 'stretch'
    target_repository: "debian-experimental"
  roles:
    - awx-instance

- hosts: localhost
  gather_facts: true
  vars:
    instance_name: awx-debian9-experimental
    action: terminate
  roles:
    - lxd-container